feat(kubetail): Added

diff --git a/tools/kubetail/Dockerfile.template b/tools/kubetail/Dockerfile.template
--- a/tools/kubetail/Dockerfile.template
+++ b/tools/kubetail/Dockerfile.template
@@ -7,9 +7,23 @@ COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
 SHELL [ "bash", "-clo", "errexit" ]
 ARG name
 ARG version
-
 RUN --mount=type=cache,target=/var/cache/uniget/download <<EOF
-url="https://github.com/kubetail-org/kubetail/releases/download/cli/v${version}/kubetail-linux-${alt_arch}.tar.gz"
+echo "### Setting architecture string for ${TARGETPLATFORM}"
+case "${arch}" in
+    x86_64)
+        export arch_suffix="amd64"
+        ;;
+    aarch64)
+        export arch_suffix="arm64"
+        ;;
+    *)
+        echo "ERROR: Unsupported architecture ${arch}."
+        exit 1
+        ;;
+esac
+echo "    Using ${arch_suffix}"
+
+url="https://github.com/kubetail-org/kubetail/releases/download/cli/v${version}/kubetail-linux-${arch_suffix}.tar.gz"
 filename="$( basename "${url}" )"
 
 check-download "${url}"
@@ -18,10 +32,10 @@ curl --silent --show-error --location --fail --output "${uniget_cache_download}/
     "${url}"
 
 tar --file="${uniget_cache_download}/${filename}" --list
-tar --file="${uniget_cache_download}/${filename}" --extract --gzip --no-same-owner \
-    --directory="${prefix}/bin"
+tar --file="${uniget_cache_download}/${filename}" --extract --gzip --directory="${prefix}/bin" --no-same-owner
 EOF
-
-
-FROM scratch
-COPY --from=prepare /uniget_bootstrap /
+RUN <<EOF
+"${prefix}/bin/kubetail" completion bash >"${prefix}/share/bash-completion/completions/kubetail"
+"${prefix}/bin/kubetail" completion fish >"${prefix}/share/fish/vendor_completions.d/kubetail.fish"
+"${prefix}/bin/kubetail" completion zsh >"${prefix}/share/zsh/vendor-completions/_kubetail"
+EOF
