fix(gwctl): Works on arm64 now

diff --git a/tools/gwctl/Dockerfile.template b/tools/gwctl/Dockerfile.template
--- a/tools/gwctl/Dockerfile.template
+++ b/tools/gwctl/Dockerfile.template
@@ -8,7 +8,22 @@ SHELL [ "bash", "-clo", "errexit" ]
 ARG name
 ARG version
 RUN --mount=type=cache,target=/var/cache/uniget/download <<EOF
-url="https://github.com/kubernetes-sigs/gwctl/releases/download/v${version}/gwctl_Linux_${arch}.tar.gz"
+echo "### Setting architecture string for ${TARGETPLATFORM}"
+case "${arch}" in
+    x86_64)
+        export arch_suffix="${arch}"
+        ;;
+    aarch64)
+        export arch_suffix="${alt_arch}"
+        ;;
+    *)
+        echo "ERROR: Unsupported architecture ${arch}."
+        exit 1
+        ;;
+esac
+echo "    Using ${arch_suffix}"
+
+url="https://github.com/kubernetes-sigs/gwctl/releases/download/v${version}/gwctl_Linux_${arch_suffix}.tar.gz"
 filename="$( basename "${url}" )"
 
 check-github-release-asset "kubernetes-sigs/gwctl" "v${version}" "${filename}"
@@ -18,4 +33,9 @@ curl --silent --show-error --location --fail --output "${uniget_cache_download}/
 tar --file="${uniget_cache_download}/${filename}" --list
 tar --file="${uniget_cache_download}/${filename}" --extract --gzip --directory="${prefix}/bin" --no-same-owner \
     gwctl
+EOF
+RUN <<EOF
+"${prefix}/bin/gwctl" completion bash >"${prefix}/share/bash-completion/completions/gwctl"
+"${prefix}/bin/gwctl" completion fish >"${prefix}/share/fish/vendor_completions.d/gwctl.fish"
+"${prefix}/bin/gwctl" completion zsh >"${prefix}/share/zsh/vendor-completions/_gwctl"
 EOF
