fix(jsonnet): Fixed build after change in github release

diff --git a/tools/jsonnet/Dockerfile.template b/tools/jsonnet/Dockerfile.template
--- a/tools/jsonnet/Dockerfile.template
+++ b/tools/jsonnet/Dockerfile.template
@@ -8,7 +8,22 @@ SHELL [ "bash", "-clo", "errexit" ]
 ARG name
 ARG version
 RUN --mount=type=cache,target=/var/cache/uniget/download <<EOF
-url="https://github.com/google/go-jsonnet/releases/download/v${version}/go-jsonnet_${version}_Linux_x86_64.tar.gz"
+echo "### Setting architecture string for ${TARGETPLATFORM}"
+case "${arch}" in
+    x86_64)
+        export arch_suffix="${arch}"
+        ;;
+    aarch64)
+        export arch_suffix="${alt_arch}"
+        ;;
+    *)
+        echo "ERROR: Unsupported architecture ${arch}."
+        exit 1
+        ;;
+esac
+echo "    Using ${arch_suffix}"
+
+url="https://github.com/google/go-jsonnet/releases/download/v${version}/go-jsonnet_Linux_${arch_suffix}.tar.gz"
 filename="$( basename "${url}" )"
 
 check-github-release-asset "google/go-jsonnet" "v${version}" "${filename}"
