feat(luksbox): Added

diff --git a/tools/luksbox/Dockerfile.template b/tools/luksbox/Dockerfile.template
--- a/tools/luksbox/Dockerfile.template
+++ b/tools/luksbox/Dockerfile.template
@@ -7,9 +7,23 @@ COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
 SHELL [ "bash", "-clo", "errexit" ]
 ARG name
 ARG version
-
 RUN --mount=type=cache,target=/var/cache/uniget/download <<EOF
-url="https://github.com/PentHertz/LUKSbox/releases/download/v${version}/luksbox-v${version}-${arch}-linux-noble.tar.gz"
+echo "### Setting architecture string for ${TARGETPLATFORM}"
+case "${arch}" in
+    x86_64)
+        export arch_suffix="${arch}"
+        ;;
+    aarch64)
+        export arch_suffix="${alt_arch}"
+        ;;
+    *)
+        echo "ERROR: Unsupported architecture ${arch}."
+        exit 1
+        ;;
+esac
+echo "    Using ${arch_suffix}"
+
+url="https://github.com/PentHertz/LUKSbox/releases/download/v${version}/luksbox-v${version}-${arch_suffix}-linux-noble.tar.gz"
 filename="$( basename "${url}" )"
 
 check-download "${url}"
@@ -18,11 +32,6 @@ curl --silent --show-error --location --fail --output "${uniget_cache_download}/
     "${url}"
 
 tar --file="${uniget_cache_download}/${filename}" --list
-tar --file="${uniget_cache_download}/${filename}" --extract --gzip --no-same-owner \
-    --directory="${prefix}/bin" \
-    "./luksbox"
+tar --file="${uniget_cache_download}/${filename}" --extract --gzip --directory="${prefix}/bin" --no-same-owner --strip-components=1 \
+    ./luksbox
 EOF
-
-
-FROM scratch
-COPY --from=prepare /uniget_bootstrap /
