fix(sbomqs): Change in github release assets

diff --git a/tools/sbomqs/Dockerfile.template b/tools/sbomqs/Dockerfile.template
--- a/tools/sbomqs/Dockerfile.template
+++ b/tools/sbomqs/Dockerfile.template
@@ -8,17 +8,31 @@ SHELL [ "bash", "-clo", "errexit" ]
 ARG name
 ARG version
 RUN --mount=type=cache,target=/var/cache/uniget/download <<EOF
-url="https://github.com/interlynk-io/sbomqs/releases/download/v${version}/sbomqs-linux-${alt_arch}"
+echo "### Setting architecture string for ${TARGETPLATFORM}"
+case "${arch}" in
+    x86_64)
+        export arch_suffix="${arch}"
+        ;;
+    aarch64)
+        export arch_suffix="${alt_arch}"
+        ;;
+    *)
+        echo "ERROR: Unsupported architecture ${arch}."
+        exit 1
+        ;;
+esac
+echo "    Using ${arch_suffix}"
+
+url="https://github.com/interlynk-io/sbomqs/releases/download/v${version}/sbomqs_${version}_Linux_${arch_suffix}.tar.gz"
 filename="$( basename "${url}" )"
 
 check-github-release-asset "interlynk-io/sbomqs" "v${version}" "${filename}"
 curl --silent --show-error --location --fail --output "${uniget_cache_download}/${filename}" \
     "${url}"
 
-install --mode=0755 \
-    "${uniget_cache_download}/${filename}" \
-    "${prefix}/bin/sbomqs"
-
+tar --file="${uniget_cache_download}/${filename}" --list
+tar --file="${uniget_cache_download}/${filename}" --extract --gzip --directory="${prefix}/bin" --no-same-owner \
+    sbomqs
 
 "${prefix}/bin/sbomqs" completion bash >"${prefix}/share/bash-completion/completions/sbomqs"
 "${prefix}/bin/sbomqs" completion fish >"${prefix}/share/fish/vendor_completions.d/sbomqs.fish"
