fix(micro): Change in github release assets

diff --git a/tools/micro/Dockerfile.template b/tools/micro/Dockerfile.template
--- a/tools/micro/Dockerfile.template
+++ b/tools/micro/Dockerfile.template
@@ -8,7 +8,21 @@ SHELL [ "bash", "-clo", "errexit" ]
 ARG name
 ARG version
 RUN --mount=type=cache,target=/var/cache/uniget/download <<EOF
-url="https://github.com/micro/micro/releases/download/v${version}/micro-v${version}-linux-${alt_arch}.tar.gz"
+echo "### Setting architecture string for ${TARGETPLATFORM}"
+case "${arch}" in
+    x86_64)
+        export arch_suffix="${arch}"
+        ;;
+    aarch64)
+        export arch_suffix="${alt_arch}"
+        ;;
+    *)
+        echo "ERROR: Unsupported architecture ${arch}."
+        exit 1
+        ;;
+esac
+echo "    Using ${arch_suffix}"
+url="https://github.com/micro/micro/releases/download/v${version}/micro_Linux_${arch_suffix}.tar.gz"
 filename="$( basename "${url}" )"
 
 check-github-release-asset "micro/micro" "v${version}" "${filename}"
