Fixed continue and simplified HEAD_REF

diff --git a/.github/workflows/automerge.yml b/.github/workflows/automerge.yml
--- a/.github/workflows/automerge.yml
+++ b/.github/workflows/automerge.yml
@@ -83,17 +83,14 @@ jobs:
                 --url "https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls/${PR}/merge" \
                 --data '{"merge_method": "rebase"}'; then
             echo "ERROR: Unable to merge PR ${PR}"
-            continue
+            exit 1
         fi
         echo "PR ${PR} has been merged"
 
-        HEAD_REF="$( jq --raw-output '.head.ref' <<<"${PR_JSON}" )"
-        echo "HEAD reference in PR ${PR} is ${HEAD_REF}"
-
-        echo "Deleting branch ${HEAD_REF}..."
+        echo "Deleting branch ${REF}..."
         if ! curl --silent --show-error --fail --request DELETE --header "Authorization: token ${GITHUB_TOKEN}" \
-                --url "https://api.github.com/repos/${GITHUB_REPOSITORY}/git/refs/heads/${HEAD_REF}"; then
-            echo "ERROR: Unable to delete branch ${HEAD_REF} from PR ${PR}"
-            continue
+                --url "https://api.github.com/repos/${GITHUB_REPOSITORY}/git/refs/heads/${REF}"; then
+            echo "ERROR: Unable to delete branch ${REF} from PR ${PR}"
+            exit 1
         fi
-        echo "Branch ${HEAD_REF} has been deleted"
+        echo "Branch ${REF} has been deleted"
