feat(nono): Added kyanos

diff --git a/tools/nono/Dockerfile.template b/tools/nono/Dockerfile.template
--- a/tools/nono/Dockerfile.template
+++ b/tools/nono/Dockerfile.template
@@ -10,7 +10,22 @@ SHELL [ "bash", "-clo", "errexit" ]
 ARG name
 ARG version
 RUN --mount=type=cache,target=/var/cache/uniget/download <<EOF
-url="https://github.com/nolabs-ai/nono/releases/download/v${version}/nono-v${version}-${alt_arch}-unknown-linux-gnu.tar.gz"
+echo "### Setting architecture string for ${TARGETPLATFORM}"
+case "${arch}" in
+    amd64|x86_64)
+        export arch_suffix="${alt_arch}"
+        ;;
+    arm64|aarch64)
+        export arch_suffix="${alt_arch}"
+        ;;
+    *)
+        echo "ERROR: Unsupported architecture ${arch}."
+        exit 1
+        ;;
+esac
+echo "    Using ${arch_suffix}"
+
+url="https://github.com/nolabs-ai/nono/releases/download/v${version}/nono-v${version}-${arch_suffix}-unknown-linux-gnu.tar.gz"
 filename="$( basename "${url}" )"
 
 check-github-release-asset "nolabs-ai/nono" "v${version}" "${filename}"
@@ -18,6 +33,7 @@ curl --silent --show-error --location --fail --output "${uniget_cache_download}/
     "${url}"
 
 tar --file="${uniget_cache_download}/${filename}" --list
-tar --file="${uniget_cache_download}/${filename}" --extract --gzip --directory="${prefix}/bin/" --no-same-owner \
-    nono
+tar --file="${uniget_cache_download}/${filename}" --extract --gzip \
+    --strip-components=0 --no-same-owner \
+    --directory="${prefix}/bin/" "nono"
 EOF
